### ISSUE TITLE
GET request fails with Content-Type: application/json when no body is present

### ISSUE THREAD

**Issue by technobulle** [adamsussman/flask-pydantic-api#4]
**Description :**

**Summary:**
When sending a GET request with Content-Type: application/json but no body, the server fails with a 400 Bad Request error. 
This is because the current logic attempts to decode a non-existent JSON body.

**Steps to reproduce:**

- Decorate a GET endpoint using @pydantic_api.
- Send a GET request to any endpoint (e.g., /exemple) with the Content-Type: application/json header.
- Ensure that no body is included in the request.

    
```
    curl -X GET \
        -H "Content-Type: application/json" \
        http://<your_server>/example
```

Expected behavior:
The server should ignore the header if no body is provided and process the request without errors.

Actual behavior:
The server raises a 400 Bad Request with the message Failed to decode JSON object.

**Comment by adamsussman** [comment]
Resolved in version 1.4.0

Thank you.
